import {
  Smartphone,
  Laptop,
  Headphones,
  Zap,
  TrendingUp,
  ShoppingCart,
  Briefcase,
  DollarSign,
  ShoppingBag,
  Globe,
  Settings,
  Users,
  Target,
  CheckSquare,
  BookOpen,
  BarChart3,
  Search,
  Mail,
  Megaphone,
  CreditCard,
  Grid,
  Gamepad2,
  Play,
  MapPin,
  Plane,
  Home,
  Heart,
  Watch,
  Apple,
  Dumbbell,
  Building2,
  Tag,
} from "lucide-react";

export const categoryIconMap: Record<string, React.ReactNode> = {
  "tech-gadgets": <Smartphone className="w-8 h-8" />,
  "smartphones": <Smartphone className="w-8 h-8" />,
  "laptops": <Laptop className="w-8 h-8" />,
  "tech-accessories": <Headphones className="w-8 h-8" />,
  "ai-tools-automation": <Zap className="w-8 h-8" />,
  "online-business-side-hustles": <TrendingUp className="w-8 h-8" />,
  "dropshipping": <ShoppingCart className="w-8 h-8" />,
  "freelancing-platforms": <Briefcase className="w-8 h-8" />,
  "passive-income-tools": <DollarSign className="w-8 h-8" />,
  "ecommerce-marketing": <ShoppingBag className="w-8 h-8" />,
  "web-hosting-domains": <Globe className="w-8 h-8" />,
  "software-saas-tools": <Settings className="w-8 h-8" />,
  "crm-tools": <Users className="w-8 h-8" />,
  "marketing-tools": <Target className="w-8 h-8" />,
  "productivity-apps": <CheckSquare className="w-8 h-8" />,
  "online-courses-education": <BookOpen className="w-8 h-8" />,
  "digital-marketing-tools": <BarChart3 className="w-8 h-8" />,
  "seo-tools": <Search className="w-8 h-8" />,
  "email-marketing": <Mail className="w-8 h-8" />,
  "ads-platforms": <Megaphone className="w-8 h-8" />,
  "payment-solutions-mobile-money": <CreditCard className="w-8 h-8" />,
  "apps-mobile-tools": <Grid className="w-8 h-8" />,
  "gaming-entertainment-platforms": <Gamepad2 className="w-8 h-8" />,
  "streaming-services-big-events": <Play className="w-8 h-8" />,
  "travel-booking-platforms": <MapPin className="w-8 h-8" />,
  "flight-booking": <Plane className="w-8 h-8" />,
  "hotel-booking": <Home className="w-8 h-8" />,
  "world-travel-tools": <Globe className="w-8 h-8" />,
  "african-travel-tools": <MapPin className="w-8 h-8" />,
  "health-fitness-apps-tools": <Heart className="w-8 h-8" />,
  "wearables": <Watch className="w-8 h-8" />,
  "diet-apps": <Apple className="w-8 h-8" />,
  "gym-tools": <Dumbbell className="w-8 h-8" />,
  "lifestyle-products-services": <Home className="w-8 h-8" />,
  "home-tech": <Home className="w-8 h-8" />,
  "personal-productivity": <Zap className="w-8 h-8" />,
  "real-estate": <Building2 className="w-8 h-8" />,
};

export function getCategoryIcon(slug: string): React.ReactNode {
  return categoryIconMap[slug] || <Tag className="w-8 h-8" />;
}
