export const categoryIcons: Record<string, string> = {
  "tech-gadgets": "Smartphone",
  "smartphones": "Smartphone",
  "laptops": "Laptop",
  "tech-accessories": "Headphones",
  "ai-tools-automation": "Zap",
  "online-business-side-hustles": "TrendingUp",
  "dropshipping": "ShoppingCart",
  "freelancing-platforms": "Briefcase",
  "passive-income-tools": "DollarSign",
  "ecommerce-marketing": "ShoppingBag",
  "web-hosting-domains": "Globe",
  "software-saas-tools": "Settings",
  "crm-tools": "Users",
  "marketing-tools": "Target",
  "productivity-apps": "CheckSquare",
  "online-courses-education": "BookOpen",
  "digital-marketing-tools": "BarChart3",
  "seo-tools": "Search",
  "email-marketing": "Mail",
  "ads-platforms": "Megaphone",
  "payment-solutions-mobile-money": "CreditCard",
  "apps-mobile-tools": "Grid",
  "gaming-entertainment-platforms": "Gamepad2",
  "streaming-services-big-events": "Play",
  "travel-booking-platforms": "MapPin",
  "flight-booking": "Plane",
  "hotel-booking": "Home",
  "world-travel-tools": "Globe",
  "african-travel-tools": "MapPin",
  "health-fitness-apps-tools": "Heart",
  "wearables": "Watch",
  "diet-apps": "Apple",
  "gym-tools": "Dumbbell",
  "lifestyle-products-services": "Home",
  "home-tech": "Home",
  "personal-productivity": "Zap",
  "real-estate": "Building2",
};

export function getIconForCategory(slug: string): string {
  return categoryIcons[slug] || "Tag";
}
